name: PR Verify
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Build project
        run: npm run build

      - name: Run tests
        id: run-tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        continue-on-error: true
