name: PR Verify
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm # Install pnpm globally

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile # Use pnpm to install dependencies with lockfile integrity

      - name: Build Angular Project
        run: pnpm build -- --configuration production

      - name: Run tests
        run: pnpm test:headless
